### ISSUE TITLE
Discuss queue's jobs relation

### ISSUE THREAD

**Issue by oldwisenir** [linnovate/replay-api#142]
splitting a one to one relation of jobs to revert tree with sub jobs...
split jobs by id if possible

**Comment by motyros** [comment]
I think what actually we need to discuss is **Transaction & transactionId** definition. 
(What about a _"transaction child"_ in case one job produce multiple jobs)

**Comment by CodeJjang** [comment]
What one to one relation are you talking about? relation between who?
Also, what do you want to achieve with the separation that you don't have today?

**Comment by CodeJjang** [comment]
The first and basic idea behind transaction was to identify whether a certain job was already done or not, in order to prevent from duplicates/inconsistencies in the system (DB/FS/Kaltura/etc...) upon job failure.

Since each transaction has one JobStatus object which is updated with the status of every job, by looking at a JobStatus with some transactionId we can see all the flow the INITIAL message has gone through - and see if it missed anything, etc.
Doesn't matter if a job produced 5 other jobs, and they produced 20 other jobs too.

If a certain job, like the captions creations or the bounding polygon creations can be done several times in a specific flow (I don't understand why you do that, in all the other jobs I handled lists instead of individual objects - we're not real time system, and when the system is overloaded we just pop another consumer)... then just don't check the "this job was already done? then skip it" test.

Making JobStatus hierarchy with childs etc would be very cumbersome and complicate a logic which should NOT be complicated:
Looking at one JobStatus object won't reflect the actual job status because we'd have to look for related JobStatus objects.
Let's take captions creations for example. 
We'll create many 'futile' JobStatus objects for every single video that the captions are created for, and then all those JobStatuses would have to be related to the original JobStatus?
And if your service produces more jobs, then all this chain will be detached from the main JobStatus object?

Instead, if the captions service (and bounding polygon service) would be able to work with a list of videos, that would be most natural way to handle the JobStatuses, as we'd keep only ONE object per flow.

The tradeoff is that those jobs would be slower, however we don't have real-time requirements, and anyway, we can still lift more consumers if the system is overloaded - so why complicate things?
All the rest of the jobs (metadata parser, insertion to mongo, attach video metadata) works on lists of objects and not one after one.
