### ISSUE TITLE
Change video status to 'ready' in the right timing

### ISSUE THREAD

**Issue by benzigdon** [linnovate/replay-api#93]
Change video status to 'ready' only after both upload to Kaltura finished and the metadata processing finished

**Comment by CodeJjang** [comment]
Closed because it is in the right timing.
We will never know when the metadata will arrive, and even if it is ever going to arrive or not.
Therefore, a video is 'ready' after it has uploaded to Kaltura regardless of the video metadata state (received / not received yet / will never be receieved...)
@kaplanlior @liran100
